/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/village": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["registerVillage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/vote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["vote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/setting": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setting"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/setting/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["settingConfirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/say": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["say"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/say-confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sayConfirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/rollcall": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rollcall"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/participate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["participateVillage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/participate-confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["participateConfirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["leave"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/daychange-check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["checkDaychange"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["commit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/comingout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["comingout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/change-skill": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["changeSkill"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/ability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ability"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirmRegisterVillage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/player/nickname": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["updateNickname"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/start-village": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["startVillage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/start-rollcall": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["startRollCall"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/say": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["say_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/say-confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sayConfirm_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/kick": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["kick"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creator/village/{villageId}/cancel-rollcall": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancelRollCall"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/participate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["participateVillage_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/no-suddenly-death": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setNoSuddenlyDeath"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/multiple-say": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["multiSay"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/dummy-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["dummyLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/change-day": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["changeDay"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/all-vote/{participantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["allRandomVote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/all-rollcall": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["allRollcall"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/all-random-vote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["allRandomVote_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}/all-draw-vote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["allDrawVote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["village"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/situation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getParticipateSituation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/{villageId}/message-list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["message"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/village/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["villageList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/skill/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["charachipList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recruiting-village-list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["recruitingVillageList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/player/{playerId}/record": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/my-player": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["myPlayer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/charachip/{charaChipId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["charachip"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/charachip/{charaChipId}/dummychara": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["dummyChara"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/charachip/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["charachipList_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chara/{charaId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["chara"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/village/{villageId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["village_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    VillageCharachipCreateBody: {
      /** Format: int32 */
      dummy_chara_id: number;
      /** Format: int32 */
      charachip_id: number;
    };
    VillageOrganizationCreateBody: {
      organization: string;
    };
    VillageRegisterBody: {
      village_name: string;
      setting: components["schemas"]["VillageSettingRegisterBody"];
    };
    VillageRuleCreateBody: {
      available_skill_request: boolean;
      open_skill_in_grave: boolean;
      visible_grave_message: boolean;
      available_suddenly_death: boolean;
      available_commit: boolean;
      available_dummy_skill: boolean;
      available_same_target_guard: boolean;
      first_divine_nowolf: boolean;
      /** Format: int32 */
      silent_seconds?: number;
      creator_game_master: boolean;
      join_password?: string;
    };
    VillageSettingRegisterBody: {
      time: components["schemas"]["VillageTimeCreateBody"];
      organization: components["schemas"]["VillageOrganizationCreateBody"];
      charachip: components["schemas"]["VillageCharachipCreateBody"];
      rule: components["schemas"]["VillageRuleCreateBody"];
    };
    VillageTimeCreateBody: {
      /** Format: date-time */
      start_datetime: string;
      /** Format: int32 */
      noon_seconds: number;
      /** Format: int32 */
      vote_seconds: number;
      /** Format: int32 */
      night_seconds: number;
    };
    VillageRegisterView: {
      /** Format: int32 */
      village_id: number;
    };
    VillageVoteBody: {
      /** Format: int32 */
      target_id: number;
    };
    VillageSayBody: {
      message: string;
      message_type: string;
      strong: boolean;
    };
    AbilityType: {
      code: string;
      name: string;
    };
    AbilityTypes: {
      list: components["schemas"]["AbilityType"][];
    };
    Camp: {
      code: string;
      name: string;
    };
    CharaImage: {
      /** Format: int32 */
      width: number;
      /** Format: int32 */
      height: number;
      image_url: string;
    };
    CharaNameView: {
      name: string;
      short_name: string;
      full_name: string;
    };
    CharaView: {
      /** Format: int32 */
      id: number;
      name: components["schemas"]["CharaNameView"];
      /** Format: int32 */
      charachip_id: number;
      image: components["schemas"]["CharaImage"];
    };
    ComingOut: {
      skill: components["schemas"]["Skill"];
    };
    DeadView: {
      code: string;
      reason: string;
      village_day: components["schemas"]["VillageDay"];
    };
    MessageContent: {
      type: components["schemas"]["MessageType"];
      text: string;
      is_strong: boolean;
    };
    MessageTimeView: {
      /** Format: int32 */
      village_day_id: number;
      /** Format: int32 */
      day: number;
      /** Format: date-time */
      datetime: string;
      /** Format: int64 */
      unix_time_milli: number;
    };
    MessageType: {
      code: string;
      name: string;
    };
    MessageView: {
      from?: components["schemas"]["VillageParticipantView"];
      time: components["schemas"]["MessageTimeView"];
      content: components["schemas"]["MessageContent"];
    };
    NoonNight: {
      code: string;
      name: string;
      is_night_time: boolean;
      is_vote_time: boolean;
      is_noon_time: boolean;
    };
    PlayerView: {
      /** Format: int32 */
      id: number;
      nickname: string;
      twitter_user_name: string;
    };
    Skill: {
      code: string;
      name: string;
      short_name: string;
      win_judge_camp: components["schemas"]["Camp"];
      ability_list: components["schemas"]["AbilityType"][];
      manual_ability_list: components["schemas"]["AbilityType"][];
      divine_result_wolf: boolean;
      psychic_result_wolf: boolean;
      sayable_skill_message_type_list: components["schemas"]["MessageType"][];
      viewable_skill_message_type_list: components["schemas"]["MessageType"][];
      count_camp?: components["schemas"]["Camp"];
      description: string;
      abilities: components["schemas"]["AbilityTypes"];
      is_fox_count: boolean;
    };
    SkillRequest: {
      first: components["schemas"]["Skill"];
      second: components["schemas"]["Skill"];
    };
    VillageDay: {
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      day: number;
      noon_night: components["schemas"]["NoonNight"];
      is_epilogue: boolean;
      /** Format: date-time */
      start_datetime: string;
      /** Format: date-time */
      end_datetime: string;
      is_night_time: boolean;
      is_vote_time: boolean;
      is_noon_time: boolean;
    };
    VillageParticipantView: {
      /** Format: int32 */
      id: number;
      chara: components["schemas"]["CharaView"];
      player?: components["schemas"]["PlayerView"];
      dead?: components["schemas"]["DeadView"];
      skill?: components["schemas"]["Skill"];
      skill_request?: components["schemas"]["SkillRequest"];
      winlose?: components["schemas"]["WinLose"];
      coming_out?: components["schemas"]["ComingOut"];
      done_roll_call: boolean;
    };
    WinLose: {
      code: string;
      name: string;
    };
    VillageRollcallBody: {
      rollcall: boolean;
    };
    VillageParticipateBody: {
      /** Format: int32 */
      chara_id: number;
      first_request_skill: string;
      second_request_skill: string;
      join_password?: string;
    };
    VillageCommitBody: {
      commit: boolean;
    };
    VillageComingOutBody: {
      skill_code?: string;
    };
    VillageChangeSkillBody: {
      first_request_skill: string;
      second_request_skill: string;
    };
    VillageAbilityBody: {
      /** Format: int32 */
      target_id?: number;
      ability_type: string;
    };
    PlayerUpdateNicknameBody: {
      nickname: string;
      twitter_user_name: string;
    };
    CreatorSayBody: {
      message: string;
    };
    CreatorKickBody: {
      /** Format: int32 */
      target_id: number;
    };
    AdminParticipateBody: {
      /** Format: int32 */
      participate_count: number;
    };
    AdminDummyLoginBody: {
      /** Format: int32 */
      target_id: number;
    };
    PersonCapacity: {
      /** Format: int32 */
      min: number;
      /** Format: int32 */
      max: number;
    };
    VillageCharachip: {
      /** Format: int32 */
      dummy_chara_id: number;
      /** Format: int32 */
      charachip_id: number;
    };
    VillageDays: {
      list: components["schemas"]["VillageDay"][];
    };
    VillageOrganizations: {
      organization: {
        [key: string]: string;
      };
    };
    VillageParticipantsView: {
      /** Format: int32 */
      count: number;
      member_list: components["schemas"]["VillageParticipantView"][];
    };
    VillagePasswordView: {
      join_password_required: boolean;
    };
    VillageRules: {
      available_skill_request: boolean;
      open_skill_in_grave: boolean;
      available_suddenly_death: boolean;
      available_commit: boolean;
      available_dummy_skill: boolean;
      available_same_target_guard: boolean;
      first_divine_nowolf: boolean;
      /** Format: int32 */
      silent_seconds?: number;
      creator_game_master: boolean;
    };
    VillageSettingsView: {
      capacity: components["schemas"]["PersonCapacity"];
      time: components["schemas"]["VillageTimeView"];
      charachip: components["schemas"]["VillageCharachip"];
      organizations: components["schemas"]["VillageOrganizations"];
      rules: components["schemas"]["VillageRules"];
      password: components["schemas"]["VillagePasswordView"];
    };
    VillageStatus: {
      code: string;
      name: string;
      is_finished: boolean;
      is_progress: boolean;
      is_recruiting: boolean;
      is_roll_calling: boolean;
      is_settled: boolean;
      is_solved: boolean;
    };
    VillageTimeView: {
      /** Format: date-time */
      start_datetime: string;
      /** Format: int32 */
      noon_seconds: number;
      /** Format: int32 */
      vote_seconds: number;
      /** Format: int32 */
      night_seconds: number;
    };
    VillageView: {
      /** Format: int32 */
      id: number;
      name: string;
      creator_player: components["schemas"]["PlayerView"];
      status: components["schemas"]["VillageStatus"];
      win_camp?: components["schemas"]["Camp"];
      setting: components["schemas"]["VillageSettingsView"];
      participants: components["schemas"]["VillageParticipantsView"];
      days: components["schemas"]["VillageDays"];
    };
    Chara: {
      /** Format: int32 */
      id: number;
      name: components["schemas"]["CharaName"];
      /** Format: int32 */
      charachip_id: number;
      image: components["schemas"]["CharaImage"];
    };
    CharaName: {
      name: string;
      short_name: string;
    };
    SituationAsParticipantView: {
      participate: components["schemas"]["VillageParticipateSituationView"];
      roll_call: components["schemas"]["VillageRollCallSituation"];
      skill_request: components["schemas"]["VillageSkillRequestSituation"];
      commit: components["schemas"]["VillageCommitSituation"];
      coming_out: components["schemas"]["VillageComingOutSituation"];
      say: components["schemas"]["VillageSaySituation"];
      ability: components["schemas"]["VillageAbilitySituationsView"];
      vote: components["schemas"]["VillageVoteSituationView"];
      creator: components["schemas"]["VillageCreatorSituation"];
    };
    VillageAbilitySituationView: {
      type: components["schemas"]["AbilityType"];
      target_list: components["schemas"]["VillageParticipantView"][];
      usable: boolean;
      available_no_target: boolean;
    };
    VillageAbilitySituationsView: {
      list: components["schemas"]["VillageAbilitySituationView"][];
    };
    VillageComingOutSituation: {
      available_coming_out: boolean;
      current_coming_out?: components["schemas"]["ComingOut"];
      selectable_skill_list: components["schemas"]["Skill"][];
    };
    VillageCommitSituation: {
      available_commit: boolean;
      committing: boolean;
    };
    VillageCreatorSituation: {
      available_creator_setting: boolean;
      available_creator_say: boolean;
      available_start_village: boolean;
      available_cancel_village: boolean;
      available_kick: boolean;
      available_modify_setting: boolean;
      available_start_roll_call: boolean;
      available_cancel_roll_call: boolean;
      viewable_spoiler: boolean;
    };
    VillageParticipateSituationView: {
      participating: boolean;
      available_participate: boolean;
      selectable_chara_list: components["schemas"]["Chara"][];
      available_leave: boolean;
      myself?: components["schemas"]["VillageParticipantView"];
    };
    VillageRollCallSituation: {
      available_roll_call: boolean;
      done_roll_call: boolean;
    };
    VillageSaySituation: {
      available_say: boolean;
      selectable_message_type_list: components["schemas"]["MessageType"][];
      default_message_type?: components["schemas"]["MessageType"];
    };
    VillageSkillRequestSituation: {
      available_skill_request: boolean;
      selectable_skill_list: components["schemas"]["Skill"][];
      skill_request?: components["schemas"]["SkillRequest"];
    };
    VillageVoteSituationView: {
      available_vote: boolean;
      target_list: components["schemas"]["VillageParticipantView"][];
      target?: components["schemas"]["VillageParticipantView"];
    };
    VillageMessageForm: {
      message_type_list?: string[];
      participant_id_list?: number[];
      /** Format: int64 */
      from?: number;
      keyword?: string;
      /** Format: int32 */
      page_size?: number;
      /** Format: int32 */
      page_num?: number;
    };
    MessagesView: {
      list: components["schemas"]["MessageView"][];
      /** Format: int32 */
      all_record_count?: number;
      /** Format: int32 */
      all_page_count?: number;
      exist_pre_page?: boolean;
      exist_next_page?: boolean;
      /** Format: int32 */
      current_page_num?: number;
    };
    VillageListForm: {
      village_status?: string[];
    };
    Dead: {
      code: string;
      reason: string;
      village_day: components["schemas"]["VillageDay"];
      is_miserable: boolean;
    };
    Player: {
      /** Format: int32 */
      id: number;
      uid: string;
      nickname: string;
      twitter_user_name: string;
      is_restricted_participation: boolean;
      participate_progress_village_id_list: number[];
      participate_finished_village_id_list: number[];
      create_progress_village_id_list: number[];
      create_finished_village_id_list: number[];
      is_available_participate: boolean;
    };
    SimpleVillageView: {
      /** Format: int32 */
      id: number;
      name: string;
      creator_player: components["schemas"]["PlayerView"];
      status: components["schemas"]["VillageStatus"];
      win_camp?: components["schemas"]["Camp"];
      setting: components["schemas"]["VillageSettingsView"];
      participants: components["schemas"]["VillageParticipants"];
      days: components["schemas"]["VillageDays"];
    };
    VillageParticipant: {
      /** Format: int32 */
      id: number;
      chara: components["schemas"]["Chara"];
      player: components["schemas"]["Player"];
      dead?: components["schemas"]["Dead"];
      is_gone: boolean;
      skill?: components["schemas"]["Skill"];
      skill_request: components["schemas"]["SkillRequest"];
      winlose?: components["schemas"]["WinLose"];
      coming_out?: components["schemas"]["ComingOut"];
      done_roll_call: boolean;
      is_alive: boolean;
      is_available_coming_out: boolean;
      is_viewable_fox_message: boolean;
      is_viewable_mason_message: boolean;
      is_available_roll_call: boolean;
      is_viewable_grave_say: boolean;
      is_sayable_grave_say: boolean;
      is_viewable_mason_say: boolean;
      is_sayable_mason_say: boolean;
      is_sayable_monologue_say: boolean;
      is_viewable_werewolf_say: boolean;
      is_sayable_werewolf_say: boolean;
      is_available_vote: boolean;
      is_dead: boolean;
      is_viewable_attack_message: boolean;
      is_viewable_fanatic_message: boolean;
      is_viewable_psychic_message: boolean;
      is_available_skill_request: boolean;
    };
    VillageParticipants: {
      /** Format: int32 */
      count: number;
      list: components["schemas"]["VillageParticipant"][];
    };
    VillagesView: {
      list: components["schemas"]["SimpleVillageView"][];
    };
    Version: {
      /** Format: int32 */
      client_version: number;
    };
    SkillsView: {
      list: components["schemas"]["Skill"][];
    };
    RecruitingVillageView: {
      /** Format: int32 */
      id: number;
      name: string;
      status: string;
      /** Format: int32 */
      participant_count: number;
      /** Format: int32 */
      participant_capacity: number;
      /** Format: int32 */
      noon_seconds: number;
      /** Format: int32 */
      vote_seconds: number;
      /** Format: int32 */
      night_seconds: number;
      start_datetime: string;
      charachip_name: string;
      url: string;
      organization: string;
    };
    RecruitingVillagesView: {
      village_list: components["schemas"]["RecruitingVillageView"][];
    };
    CampRecord: {
      camp: components["schemas"]["Camp"];
      /** Format: int32 */
      participate_count: number;
      /** Format: int32 */
      win_count: number;
      /** Format: float */
      win_rate: number;
      /** Format: int32 */
      lose_count: number;
      /** Format: float */
      lose_rate: number;
      /** Format: int32 */
      draw_count: number;
      /** Format: float */
      draw_rate: number;
    };
    ParticipateVillageView: {
      village: components["schemas"]["VillageView"];
      participant: components["schemas"]["VillageParticipantView"];
    };
    PlayerRecordsView: {
      player: components["schemas"]["PlayerView"];
      whole_record: components["schemas"]["Record"];
      camp_record_list: components["schemas"]["CampRecord"][];
      skill_record_list: components["schemas"]["SkillRecord"][];
      participate_village_list: components["schemas"]["ParticipateVillageView"][];
    };
    Record: {
      /** Format: int32 */
      participate_count: number;
      /** Format: int32 */
      win_count: number;
      /** Format: float */
      win_rate: number;
      /** Format: int32 */
      lose_count: number;
      /** Format: float */
      lose_rate: number;
      /** Format: int32 */
      draw_count: number;
      /** Format: float */
      draw_rate: number;
    };
    SkillRecord: {
      skill: components["schemas"]["Skill"];
      /** Format: int32 */
      participate_count: number;
      /** Format: int32 */
      win_count: number;
      /** Format: float */
      win_rate: number;
      /** Format: int32 */
      lose_count: number;
      /** Format: float */
      lose_rate: number;
      /** Format: int32 */
      draw_count: number;
      /** Format: float */
      draw_rate: number;
    };
    MyselfPlayerView: {
      /** Format: int32 */
      id: number;
      nickname: string;
      twitter_user_name: string;
      available_create_village: boolean;
      participate_progress_villages: components["schemas"]["VillagesView"];
      participate_finished_villages: components["schemas"]["VillagesView"];
      create_progress_villages: components["schemas"]["VillagesView"];
      create_finished_villages: components["schemas"]["VillagesView"];
    };
    CharachipView: {
      /** Format: int32 */
      id: number;
      name: string;
      designer: components["schemas"]["Designer"];
      description_url: string;
      chara_list: components["schemas"]["Chara"][];
    };
    Designer: {
      /** Format: int32 */
      id: number;
      name: string;
    };
    CharachipsView: {
      list: components["schemas"]["CharachipView"][];
    };
    DebugVillageView: {
      /** Format: int32 */
      id: number;
      name: string;
      creator_player: components["schemas"]["PlayerView"];
      status: components["schemas"]["VillageStatus"];
      setting: components["schemas"]["VillageSettingsView"];
      participants: components["schemas"]["VillageParticipantsView"];
      days: components["schemas"]["VillageDays"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  registerVillage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageRegisterBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["VillageRegisterView"];
        };
      };
    };
  };
  vote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageVoteBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setting: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageRegisterBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  settingConfirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageRegisterBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  say: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageSayBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sayConfirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageSayBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MessageView"];
        };
      };
    };
  };
  rollcall: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageRollcallBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  participateVillage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageParticipateBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  participateConfirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageParticipateBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  leave: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  checkDaychange: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  commit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageCommitBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  comingout: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageComingOutBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changeSkill: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageChangeSkillBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ability: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageAbilityBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  confirmRegisterVillage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VillageRegisterBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateNickname: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlayerUpdateNicknameBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  startVillage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  startRollCall: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  say_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatorSayBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sayConfirm_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatorSayBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MessageView"];
        };
      };
    };
  };
  kick: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatorKickBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancelRollCall: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  participateVillage_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminParticipateBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setNoSuddenlyDeath: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  multiSay: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  dummyLogin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminDummyLoginBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changeDay: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  allRandomVote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
        participantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  allRollcall: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  allRandomVote_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  allDrawVote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  village: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["VillageView"];
        };
      };
    };
  };
  getParticipateSituation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SituationAsParticipantView"];
        };
      };
    };
  };
  message: {
    parameters: {
      query: {
        form: components["schemas"]["VillageMessageForm"];
      };
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MessagesView"];
        };
      };
    };
  };
  villageList: {
    parameters: {
      query: {
        form: components["schemas"]["VillageListForm"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["VillagesView"];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["Version"];
        };
      };
    };
  };
  charachipList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SkillsView"];
        };
      };
    };
  };
  recruitingVillageList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["RecruitingVillagesView"];
        };
      };
    };
  };
  stats: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        playerId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PlayerRecordsView"];
        };
      };
    };
  };
  myPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MyselfPlayerView"];
        };
      };
    };
  };
  charachip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        charaChipId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CharachipView"];
        };
      };
    };
  };
  dummyChara: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        charaChipId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["Chara"];
        };
      };
    };
  };
  charachipList_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CharachipsView"];
        };
      };
    };
  };
  chara: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        charaId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["Chara"];
        };
      };
    };
  };
  village_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        villageId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DebugVillageView"];
        };
      };
    };
  };
}
